# Generated by Django 3.2.6 on 2021-08-28 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hubmanager', '0002_logichub'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HubLoader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hmanagers', to='hubmanager.hubmanager')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='greenloaders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
