# Generated by Django 3.2.6 on 2021-09-01 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hubmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubLoader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hmanagers', to='hubmanager.hubmanager')),
            ],
        ),
    ]
