# Generated by Django 3.2.6 on 2021-08-28 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenadmin', '0002_greenadmin_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hubname', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hubowner', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='hubowners', to='greenadmin.greenadmin')),
            ],
        ),
    ]
