# Generated by Django 3.2.6 on 2021-08-28 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenadmin', '0003_logichub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logichub',
            name='hubowner',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hubowners', to='greenadmin.greenadmin'),
        ),
    ]
