# Generated by Django 3.2.6 on 2021-08-28 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenadmin', '0004_alter_logichub_hubowner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogicHub',
        ),
    ]
