# Generated by Django 3.2.6 on 2021-09-01 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('greenadmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='greenadmin.greenadmin')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagename', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField()),
                ('orderstat', models.CharField(choices=[('confirmed', 'confirmed'), ('shipped', 'shipped'), ('out for delivery', 'out for delivery'), ('delivered', 'delivered')], default='confirmed', max_length=40)),
                ('to_customer_name', models.CharField(max_length=100)),
                ('to_customer_email', models.CharField(max_length=100)),
                ('supplier', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='customersuppliers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
