# Generated by Django 3.2.6 on 2021-08-27 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagename', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
                ('orderstat', models.CharField(choices=[('confirmed', 'confirmed'), ('shipped', 'shipped'), ('out for delivery', 'out for delivery'), ('delivered', 'delivered')], default='confirmed', max_length=40)),
                ('to_customer_name', models.CharField(max_length=100)),
                ('to_customer_email', models.CharField(max_length=100)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customersuppliers', to='supplier.supplier')),
            ],
        ),
    ]
