# Generated by Django 3.2.6 on 2021-08-27 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier', '0002_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='supplier',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='customersuppliers', to=settings.AUTH_USER_MODEL),
        ),
    ]
