# Generated by Django 3.2.6 on 2021-08-28 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('greenadmin', '0004_alter_logichub_hubowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='greenadmin.greenadmin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='greenusers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
