# Generated by Django 3.2.6 on 2021-08-28 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenadmin', '0005_delete_logichub'),
        ('hubmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hubname', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hubmanager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hubmanagers', to='hubmanager.hubmanager')),
                ('hubowner', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hubowners', to='greenadmin.greenadmin')),
            ],
        ),
    ]
