# Generated by Django 3.2.6 on 2021-09-01 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hubmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubmanager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='greenusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
