# Generated by Django 3.2.6 on 2021-09-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0002_hubloader_user'),
        ('hubmanager', '0002_hubmanager_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='logichub',
            name='loaders',
            field=models.ManyToManyField(blank=True, to='loader.HubLoader'),
        ),
    ]
