# Generated by Django 3.2.6 on 2021-09-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubmanager', '0004_alter_logichub_loaders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logichub',
            name='loaders',
        ),
    ]
